name: DLUX THE LIGHT
favicon: null
layout_spectrum: 0.3725640734191984
typography_spectrum: 0.4202352906577289
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7962307506240904
  lightness: 0.9418742258567363
  saturation: 0.027214424684643745
  rhythmicContrast: 0.7909081089310348
purpose: []
